// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "brightness.enabled": boolean;
      "contrast.enabled": boolean;
      "saturate.enabled": boolean;
      "grayscale.enabled": boolean;
      "sepia.enabled": boolean;
      "hue-rotate.enabled": boolean;
      "invert.enabled": boolean;
      "brightness.default": number;
      "contrast.default": number;
      "saturate.default": number;
      "grayscale.default": number;
      "sepia.default": number;
      "hue-rotate.default": number;
      "invert.default": number;
      "brightness.values": string;
      "contrast.values": string;
      "saturate.values": string;
      "grayscale.values": string;
      "sepia.values": string;
      "hue-rotate.values": string;
      "invert.values": string;
    };
  }
}
